### ISSUE TITLE
Error with database

### ISSUE THREAD

**Issue by KochyanLV** [MilitaryGuineaPig/Car-Rent-Ap-Qt#2]
Bro, don't understand how I can run this project. Maybe I should download databases? Thank you very much in advance! 
![image](https://user-images.githubusercontent.com/90781795/210015015-ac428494-0091-4012-8c07-bde28574f877.png)
![image](https://user-images.githubusercontent.com/90781795/210015039-4a7cd270-8f9d-4f8e-9e0d-27d89c5447d2.png)

**Comment by MilitaryGuineaPig** [comment]
Wassup, so first of all watch some videos about MySql and how it works. Then google to get how to connect MySql to a Qt app.  And then if something is unclear, don't hesitate to ask :)
