### ISSUE TITLE
Database's screenshots

### ISSUE THREAD

**Issue by klv0510** [MilitaryGuineaPig/Car-Rent-Ap-Qt#3]
Hello, mate. Could you please add screenshots of data in your 3 tables. I have problems with opening ibd files. So I want to create database myself. Or at least show please names of the columns in tables. Thank you very much in advance! You have a wonderful project!

**Comment by MilitaryGuineaPig** [comment]
car db
![image](https://user-images.githubusercontent.com/113282778/210991534-bd2deba8-d500-42d2-a63b-cfdce598b95e.png)
rent db
![image](https://user-images.githubusercontent.com/113282778/210991831-72c17a28-d082-4baa-aa03-ec3f0e745252.png)
users db
![image](https://user-images.githubusercontent.com/113282778/210992018-c89d1061-9966-4cb9-8123-93abf22176d4.png)
